# Generated by Django 3.2.5 on 2023-02-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20230222_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtescontract',
            name='blank',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='stamped',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
