# Generated by Django 3.2.5 on 2023-02-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_ownloc'),
        ('docs', '0004_auto_20230222_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtescontract',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.ownloc'),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='blank',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.clientloc'),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='stamped',
            field=models.BooleanField(default=True),
        ),
    ]
