# Generated by Django 3.2.5 on 2023-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20230222_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtescontract',
            name='agent',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='customer',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
