# Generated by Django 3.2.5 on 2023-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20230224_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtescontract',
            name='blank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='standardtescontract',
            name='stamped',
            field=models.BooleanField(default=True),
        ),
    ]
