# Generated by Django 3.2.5 on 2023-02-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_ownloc'),
        ('docs', '0009_auto_20230224_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtescontract',
            name='agent',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companies.ownloc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardtescontract',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='companies.clientloc'),
            preserve_default=False,
        ),
    ]
