# Generated by Django 3.2.5 on 2023-02-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_ownloc'),
        ('docs', '0012_auto_20230225_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtescontract',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.ownloc'),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.clientloc'),
        ),
    ]
