# Generated by Django 3.2.5 on 2023-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_alter_standardtescontract_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtescontract',
            name='contract_date',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='standardtescontract',
            name='valid_until',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
