# Generated by Django 3.2.5 on 2023-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('pos_per_acc', models.CharField(max_length=250)),
                ('position_nom', models.CharField(max_length=250)),
                ('person_nom', models.CharField(max_length=250)),
                ('acting_on', models.CharField(max_length=100)),
                ('legal_addr', models.CharField(max_length=500)),
                ('postal_addr', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=250)),
                ('bic', models.CharField(max_length=50)),
                ('curr_acc', models.CharField(max_length=250)),
                ('corr_acc', models.CharField(max_length=250)),
                ('inn', models.CharField(max_length=250)),
                ('kpp', models.CharField(max_length=250)),
                ('ogrn', models.CharField(max_length=250)),
                ('okpo', models.CharField(max_length=250)),
            ],
        ),
    ]
