# Generated by Django 3.2.5 on 2023-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('pos_per_acc', models.CharField(max_length=250)),
                ('position_nom', models.CharField(max_length=250)),
                ('person_nom', models.CharField(max_length=250)),
                ('acting_on', models.CharField(max_length=100)),
                ('legal_addr', models.CharField(max_length=500)),
                ('postal_addr', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
