# Generated by Django 3.2.5 on 2023-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyint'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloc',
            name='company_type',
            field=models.CharField(default='Общество с ограниченной ответственностью', max_length=100),
        ),
    ]
