# Generated by Django 3.2.5 on 2023-02-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20230219_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyloc',
            name='acting_on',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='corr_acc',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='curr_acc',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='legal_addr',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='okpo',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='pass_issued_by',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='pass_issued_code',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='pass_issued_date',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='passport_series',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='person_nom',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='pos_per_acc',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='position_nom',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='postal_addr',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='registration_addr',
        ),
        migrations.RemoveField(
            model_name='companyloc',
            name='tel',
        ),
    ]
