# Generated by Django 3.2.5 on 2023-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20230219_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(default='-', max_length=100)),
                ('company_name', models.CharField(default='-', max_length=250)),
                ('pos_per_acc', models.CharField(default='-', max_length=250)),
                ('position_nom', models.CharField(default='-', max_length=250)),
                ('person_nom', models.CharField(default='-', max_length=250)),
                ('acting_on', models.CharField(default='-', max_length=100)),
                ('legal_addr', models.CharField(default='-', max_length=500)),
                ('passport_series', models.CharField(default='-', max_length=250)),
                ('passport_number', models.CharField(default='-', max_length=250)),
                ('pass_issued_by', models.CharField(default='-', max_length=250)),
                ('pass_issued_date', models.CharField(default='-', max_length=100)),
                ('pass_issued_code', models.CharField(default='-', max_length=500)),
                ('postal_addr', models.CharField(default='-', max_length=500)),
                ('registration_addr', models.CharField(default='-', max_length=500)),
                ('tel', models.CharField(default='-', max_length=100)),
                ('email', models.CharField(default='-', max_length=100)),
                ('bank_name', models.CharField(default='-', max_length=250)),
                ('bic', models.CharField(default='-', max_length=50)),
                ('curr_acc', models.CharField(default='-', max_length=250)),
                ('corr_acc', models.CharField(default='-', max_length=250)),
                ('inn', models.CharField(default='-', max_length=250)),
                ('kpp', models.CharField(default='-', max_length=250)),
                ('ogrn', models.CharField(default='-', max_length=250)),
                ('okpo', models.CharField(default='-', max_length=250)),
            ],
        ),
    ]
